---
- hosts: all
  gather_subset:
    - distribution
    - hardware
  vars_files:
    - vars/users.yml
  handlers:
    - name: restart-sshd
      service:
        name: sshd
        state: restarted

    - name: restart-libvirtd
      service:
        name: libvirtd
        state: restarted

    - name: restart-journald
      service:
        name: systemd-journald
        state: restarted

    - name: update-grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: reboot-machine
      reboot:

  tasks:
    - name: Repos
      include: tasks/repos.yml

    - name: Packages
      include: tasks/packages.yml

    - name: Services
      include: tasks/services.yml

    - name: System configuration
      include: tasks/system_configuration.yml

    - name: User
      include: tasks/user.yml

    - name: User configuration
      become: true
      become_user: '{{ user.username }}'
      block:
        - name: neovim
          include: tasks/nvim.yml

        - name: git
          include: tasks/git.yml

        - name: GTK
          include: tasks/gtk.yml

        - name: Firefox
          include: tasks/firefox.yml

        - name: Dconf
          include: tasks/dconf.yml

        - name: Flatpak
          include: tasks/flatpak.yml

    - name: Final cleanup
      include: tasks/cleanup.yml
