---
- hosts: all
  gather_subset:
    - distribution
    - hardware
  vars_files:
    - vars/users.yml
  handlers:
    - name: restart-sshd
      service:
        name: sshd
        state: restarted

    - name: restart-libvirtd
      service:
        name: libvirtd
        state: restarted

    - name: restart-journald
      service:
        name: systemd-journald
        state: restarted

    - name: update-grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: reboot-machine
      reboot:

  tasks:
    - name: Repos
      include_tasks: tasks/repos.yml

    - name: Packages
      include_tasks: tasks/packages.yml

    - name: Services
      include_tasks: tasks/services.yml

    - name: System configuration
      include_tasks: tasks/system_configuration.yml

    - name: User
      include_tasks: tasks/user.yml

    - name: User configuration
      become: true
      become_user: '{{ user.username }}'
      block:
        - name: neovim
          include_tasks: tasks/nvim.yml

        - name: git
          include_tasks: tasks/git.yml
          tags: devel

        - name: scripts
          include_tasks: tasks/user_scripts.yml
          tags:
            - devel
            - workstation

        # - name: GTK
        #   include_tasks: tasks/gtk.yml
        #   tags: workstation

        - name: Firefox
          include_tasks: tasks/firefox.yml
          tags: workstation

        - name: Dconf
          include_tasks: tasks/dconf.yml
          tags: workstation

        - name: Flatpak
          include_tasks: tasks/flatpak.yml
          tags: workstation

    - name: Final cleanup
      include_tasks: tasks/cleanup.yml
