- name: Copy the dconf config files
  copy:
    src: './dconf'
    dest: '/tmp/'
    mode: '0644'

- shell: dbus-launch dconf load /{{ item | replace ('_', '/') }}/ < {{ item }}
  args:
    chdir: /tmp/dconf
    stdin_add_newline: false
  loop:
    - system
    - com_gexperts_Tilix
    - org_gnome_desktop
    - org_gnome_mutter
    - org_gnome_shell
    - org_gnome_settings-daemon_plugins

