- name: Copy the dconf config files
  copy:
    src: './dconf'
    dest: '/tmp/'
    mode: '0755'

- name: Copy the populating Python script
  copy:
    src: './dconf.py'
    dest: '/tmp/'
    mode: '0755'

- name: Populate the dconf database from config files
  shell:
    cmd: '/tmp/dconf.py'
    chdir: '/tmp/'

