---
- name: copy global git configs
  copy:
    src: '../files/git/{{ item }}'
    dest: '/home/{{ user.username }}/.{{ item }}'
  loop:
    - 'gitconfig'
    - 'gitconfig-personal'
    - 'gitignore'

- name: Copy tag application script
  copy:
    src: '../files/git/git-apply-tag'
    dest: '/home/{{ user.username }}/bin/git-apply-tag'
    mode: '0755'

- name: Create the HOME/git directory
  file:
    path: '/home/{{ user.username }}/git'
    owner: '{{ user.username }}'
    group: '{{ user.username }}'
    state: directory
