---
- set_fact:
    config_dir: '/home/{{ user.username }}/.config/nvim'

- name: install PyPi dependencies (NVIM)
  pip:
    name:
      - jedi
      - neovim
    extra_args: --user

- name: create config directory hierarchy (NVIM)
  file:
    path: '{{ config_dir }}/autoload'
    state: directory

- name: install vim-plug manager (NVIM)
  get_url:
    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ config_dir }}/autoload/plug.vim'

- name: copy config (NVIM)
  copy:
    src: '../files/init.vim'
    dest: '{{ config_dir }}'

- name: install plugins (NVIM)
  command: nvim "+silent! PlugInstall!" +qall!

- name: Adjust the git patch tags keyboard shortcuts
  block:
    - name: Adjust the \'Reviewed-by\' shortcut
      lineinfile:
        path: '/home/{{ user.username }}/.vim/git_patch_tags.vim'
        regexp: '^(.*)rev (:call GitReviewed.*$)'
        line: '\1rb \2'
        backrefs: yes

    - name: Adjust the \'Signed-off-by\' shortcut
      lineinfile:
        path: '/home/{{ user.username }}/.vim/git_patch_tags.vim'
        regexp: '^(.*)sob (:call GitSignOff.*$)'
        line: '\1sb \2'
        backrefs: yes
