- name: Remove generic unwanted packages
  package:
    state: absent
    name: "{{ item }}"
  ignore_errors: true
  loop:
    - anaconda
    - NetworkManager-adsl
    - NetworkManager-openconnect
    - NetworkManager-pptp
    - NetworkManager-team
    - NetworkManager-vpnc
    - NetworkManager-wwan
    - telnet

- name: Remove workstation unwanted packages
  yum:
    state: absent
    name: "{{ item }}"
  loop:
      - baobab
      - cheese
      - evolution
      - gnome-abrt
      - gnome-boxes
      - gnome-calendar
      - gnome-clocks
      - gnome-contacts
      - gnome-disk-utility
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-photos
      - "gnome-shell-extension*"
      - gnome-terminal
      - gnome-weather
      - "*libreoffice*"
      - "qt*"
      - rhythmbox
      - totem
  tags:
    - workstation

- name: Update all packages
  package:
    name: "*"
    state: latest
  register: result

- name: Install core packages
  package:
    state: latest
    name: "{{ item }}"
  loop:
    - bash-completion
    - ethtool
    - htop
    - ltrace
    - man-pages
    - mc
    - ncdu
    - neovim
    - podman
    - rpmconf
    - rsync
    - strace
    - tmux
    - tree
    - unzip
    - util-linux
    - virt-what
    - wget
    - "{{ ansible_pkg_mgr }}-utils"
    - "python{{ ansible_python_version.split('.')[0] }}-pip"

- name: Install development packages
  package:
    state: latest
    name: "{{ item }}"
  loop:
    - black
    - gdb
    - git
    - git-publish
    - git-review
    - ipython3
    - libguestfs-tools
    - libvirt
    - libvirt-nss
    - make
    - meson # drop this one once I move it to a dedicated libvirt role
    - patch
    - python3-devel
    - python3-dnf-plugin-system-upgrade
    - rpm-build
    - tig
    - virt-install
    - valgrind
  tags:
    - devel

- name: Install core workstation packages
  package:
    state: latest
    name: "{{ item }}"
  loop:
    - dbus-x11 # provides the dbus-launch command which the dconf task needs
    - dconf-editor
    - ffmpeg-libs
    - gnome-tweaks
    - NetworkManager-tui
    - tilix
    - tuned
    - virt-manager
  ignore_errors: true
  tags: workstation

- name: Install extra packages (CLI)
  package:
    state: latest
    name: "{{ item }}"
  loop:
    - android-tools
    - ansible
    - geteltorito
    - lm_sensors
    - powerline
    - python3-flake8
    - python3-glances
    - python3-ipdb
    - vim-powerline
    - zsh
  tags:
    - extras-cli

- name: Install extra packages (GUI)
  package:
    state: latest
    name: "{{ item }}"
  loop:
    - bsd-games # contains the wtf command :)
    - flatpak
    - gimp
    - gnome-shell-extension-drive-menu
    - gnome-shell-extension-launch-new-instance
    - gnome-shell-extension-suspend-button
    - gnome-shell-extension-system-monitor-applet
    - inkscape
    - meld
    - playerctl
    - pidgin
    - seahorse
    - thunderbird
    - vlc
    - wireshark
    - youtube-dl
  ignore_errors: true
  tags:
    - extras-gui
