- name: Update all packages
  package:
    name: "*"
    state: latest
  register: result

- name: Install the core set of wanted packages
  package:
    state: latest
    name:
      - bash-completion
      - ethtool
      - git
      - htop
      - man-pages
      - mc
      - ncdu
      - neovim
      - podman
      - rpmconf
      - rsync
      - tmux
      - tree
      - tuned
      - unzip
      - util-linux
      - wget
      - "{{ ansible_pkg_mgr }}-utils"
      - "python{{ ansible_python_version.split('.')[0] }}-pip"

- name: Install development packages
  package:
    state: latest
    name:
      - black
      - gdb
      - gcc
      - git-publish
      - git-review
      - ipython3
      - guestfs-tools
      - libvirt
      - libvirt-nss
      - ltrace
      - make
      - meson # drop this one once I move it to a dedicated libvirt role
      - patch
      - python3-devel
      - python3-dnf-plugin-system-upgrade
      - python3-flake8
      - python3-ipdb
      - python3-wheel
      - rpm-build
      - ShellCheck
      - strace
      - tig
      - vim-enhanced # provides vimdiff
      - virt-install
      - virt-what
      - valgrind
  tags:
    - devel

- name: Install workstation packages
  package:
    state: latest
    name:
      - '@Fedora Workstation'
      - android-tools
      - ansible
      - bsd-games # contains the wtf command :)
      - dbus-x11 # provides the dbus-launch command which the dconf task needs
      - dconf-editor
      - ffmpeg-libs
      - flatpak
      - glances
      - gimp
      - gnome-tweaks
      - inkscape
      - lm_sensors
      - NetworkManager-tui
      - playerctl
      - powerline
      - pidgin
      - thunderbird
      - tilix
      - virt-manager
      - vlc
      - wireshark
      - zsh
    install_weak_deps: false
    skip_broken: true
    nobest: true
  tags:
    - workstation

- name: Install TLP battery management SW
  package:
    state: latest
    name: tlp
  when:
    - ansible_system_vendor | lower == 'lenovo'
    - '"thinkpad" in ansible_product_version | lower'

- name: Remove generic unwanted packages
  package:
    state: absent
    name:
      - anaconda
      - NetworkManager-adsl
      - NetworkManager-openconnect
      - NetworkManager-pptp
      - NetworkManager-team
      - NetworkManager-vpnc
      - NetworkManager-wwan
      - telnet
  ignore_errors: true
  loop:
    - anaconda
    - NetworkManager-adsl
    - NetworkManager-openconnect
    - NetworkManager-pptp
    - NetworkManager-team
    - NetworkManager-vpnc
    - NetworkManager-wwan
    - telnet

- name: Remove workstation unwanted packages
  package:
    state: absent
    name:
      - baobab
      - cheese
      - evolution
      - gnome-abrt
      - gnome-boxes
      - gnome-calendar
      - gnome-clocks
      - gnome-contacts
      - gnome-disk-utility
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-photos
      - "gnome-shell-extension*"
      - gnome-terminal
      - gnome-weather
      - "qt*"
      - rhythmbox
      - totem
  ignore_errors: true
  tags:
    - workstation
