---
- include_vars: vars/rpmfusion.yml

- block:
  - name: Enable RPM fusion
    dnf:
      name:
        - "{{ free.rpm }}"
        - "{{ nonfree.rpm }}"
      disable_gpg_check: true
      state: present

  - name: Enable virt-preview repo
    command: "dnf copr enable -y @virtmaint-sig/virt-preview"
    args:
      warn: false
    tags:
      - devel
  when:
    - ansible_distribution  == "Fedora"
