---
- include_vars: vars/rpmfusion.yml

- block:
  - name: Import RPM fusion GPG keys
    rpm_key:
      key: "{{ item }}"
      state: present
    loop:
      - "{{ free.gpg }}"
      - "{{ nonfree.gpg }}"

  - name: Enable RPM fusion
    dnf:
      name:
        - "{{ free.rpm }}"
        - "{{ nonfree.rpm }}"
      state: present

- name: Enable virt-preview repo
  command: "dnf copr enable -y @virtmaint-sig/virt-preview"
  args:
    warn: false
  tags:
    - devel
