---
- include_vars: vars/rpmfusion.yml

- block:
    - name: Install various distribution RPM keys
      dnf:
        name:
          - distribution-gpg-keys
        state: latest

    - name: import RPM fusion GPG keys
      rpm_key:
        key: "{{ gpg_install_path }}/RPM-GPG-KEY-rpmfusion-{{ item }}-fedora-{{ ansible_distribution_version }}"
        state: present
      loop: "{{ rpmfusion.keys() | list }}"

    - name: Enable RPM fusion
      dnf:
        name:
          - "{{ rpmfusion.free.rpm }}"
          - "{{ rpmfusion.nonfree.rpm }}"
        state: present
  when:
    - ansible_distribution  == "Fedora"
