---
- include_vars: vars/rpmfusion.yml

- name: Enable RPM fusion
  dnf:
    name:
      - "{{ free }}"
      - "{{ nonfree }}"

    # Uncomment the below parameter if installation fails with GPG verification
    # of the RPMFusion repos, normally it doesn't happen, but sometimes it does
    #disable_gpg_check: yes
    state: present

- name: Enable virt-preview repo
  command: "dnf copr enable -y @virtmaint-sig/virt-preview"
  args:
    warn: false
  tags:
    - devel
