- name: Enable services
  block:
    - name: Enable generic services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - cups-browsed
        - sshd

    - name: Enable libvirt service
      service:
        name: libvirtd
        state: started
        enabled: yes
      tags:
        - devel

# run this only on baremetal machines
- name: Enable baremetal services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  when: ansible_system_vendor != "QEMU"
  loop:
    - fstrim.timer

- name: Make runlevel 5 default
  block:
    - command: "systemctl get-default"
      changed_when: false
      register: systemdefault

    - name: Make runlevel 5 default
      command: "systemctl set-default graphical.target"
      when: "'graphical' not in systemdefault.stdout"
  tags:
    - workstation
