- name: Enable services
  block:
    - name: Enable {{ item }}
      service:
        name: '{{ item }}'
        state: started
        enabled: yes
      loop:
        - sshd
        - systemd-resolved

    - name: Enable libvirt service
      service:
        name: "{{ item }}.socket"
        state: started
        enabled: yes
      loop:
        - virtqemud
        - virtnwfilterd
        - virtnetworkd
        - virtstoraged
      tags:
        - workstation
        - devel

# run this only on baremetal machines
- name: Enable baremetal services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  when: ansible_system_vendor != "QEMU"
  loop:
    - fstrim.timer

- name: Make runlevel 5 default
  block:
    - command: "systemctl get-default"
      changed_when: false
      register: systemdefault

    - name: Make runlevel 5 default
      command: "systemctl set-default graphical.target"
      when: "'graphical' not in systemdefault.stdout"
  tags:
    - workstation
