---
- name: Create ~/bin directory
  file:
    path: '/home/{{ user.username }}/bin'
    state: directory
    mode: '0700'
    owner: '{{ user.username }}'
    group: '{{ user.username }}'

- name: Copy scripts
  copy:
    src: '{{ item }}'
    dest: '/home/{{ user.username }}/bin/'
    owner: '{{ user.username }}'
    group: '{{ user.username }}'
    mode: '0755'
  with_fileglob:
    - '../files/bin/*'
