---
- name: Set root password
  user:
    name: root
    password: '{{ root_password }}'

- name: Set custom root shell prompt
  lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\033[1;31m\]\u@\h \[\033[0m\]\[\033[1;34m\]\W # \[\033[0m\]"'
    state: present

- name: Override default editor for root
  lineinfile:
    path: /root/.bashrc
    line: "export EDITOR='nvim'"
    state: present

- name: Create '{{ user.username }}' user account
  user:
    name: '{{ user.username }}'
    groups: '{{ user.groups }}'
    comment: '{{ user.gecos }}'
    password: '{{ user.password }}'
    uid: 1234

- name: Create an SSH directory
  file:
    path: '/home/{{ user.username }}/.ssh'
    state: directory
    mode: '0700'
    owner: '{{ user.username }}'
    group: '{{ user.username }}'

- name: Touch the SSH config
  file:
    path: '/home/{{ user.username }}/.ssh/config'
    state: touch
    mode: '0600'
    owner: '{{ user.username }}'
    group: '{{ user.username }}'

- name: Copy bash configuration
  copy:
    src: '../files/bash/'
    dest: '/home/{{ user.username }}/.bash.d'
    owner: '{{ user.username }}'
    group: '{{ user.username }}'

- name: Override bashrc
  file:
    src: '/home/{{ user.username }}/.bash.d/bashrc'
    dest: '/home/{{ user.username }}/.bashrc'
    force: true
    mode: '0660'
    state: link
    owner: '{{ user.username }}'
    group: '{{ user.username }}'

- name: Override flake8
  copy:
    src: '../files/flake8'
    dest: '/home/{{ user.username }}/.config/'
    owner: '{{ user.username }}'
    group: '{{ user.username }}'

- block:
    - name: Disable trackers for the user, part I
      file:
        owner: '{{ user.username }}'
        group: '{{ user.username }}'
        mode: '0755'
        path: '/home/{{ user.username }}/.config/systemd/user'
        state: directory
      tags: workstation

    - name: Disable trackers for the user, part II
      file:
        owner: '{{ user.username }}'
        group: '{{ user.username }}'
        src: '/dev/null'
        dest: '/home/{{ user.username }}/.config/systemd/user/{{ item }}'
        state: link
      loop:
        - tracker-extract.service
        - tracker-miner-apps.service
        - tracker-miner-fs.service
        - tracker-miner-rss.service
        - tracker-store.service
        - tracker-writeback.service
      tags: workstation

    - name: Disable trackers for the user, part III
      command: restorecon -Rv '/home/{{ user.username }}/.config/systemd'
      changed_when: false
      tags: workstation
